run:
    python cleaning.py
    python scraping.py
    python exploration.py

cleaning:
    python cleaning.py

scraping:
    python scraping.py

exploration:
    python exploration.py

clean:
    rm -rf __pycache__